
# - [[flancian]]
#   - this file is meant to be consumed by [[agora bridge]]: https://github.com/flancian/agora-bridge.
#   - for a specification of this format, please consult https://anagora.org/agora-bridge.
#   - for instructions to set up a fully working [[agora]] using this and other repos, please consult https://anagora.org/agora-install or the root repository: https://github.com/flancian/agora.

- target: garden/flancian
  url: https://github.com/flancian/garden.git
  edit: https://github.com/flancian/garden/edit/master/{path}
  web: https://github.com/flancian/garden/blob/master/{path}
  protocol: git
  format: wikivim

- target: stoa/doc.anagora.org
  url: https://github.com/flancia-coop/doc.anagora.org
  protocol: git
  edit: https://doc.anagora.org/{slug}?edit
  format: stoa

- target: garden/flancia.org
  url: https://github.com/flancian/flancia
  protocol: git
  format: nikola
  edit: https://github.com/flancian/flancia/edit/master/{path}
  support: https://flancia.org

- target: garden/bitwäscherei
  url: https://github.com/bitwaescherei/bitwaescherei.git
  web: https://bitwaescherei.ch
  edit: https://github.com/bitwaescherei/bitwaescherei/edit/master/{path}
  format: obsidian

- target: garden/sgmk
  url: https://wiki.sgmk-ssam.ch/api.php
  web: https://wiki.sgmk-ssam.ch/wiki/{slug}
  format: mediawiki

- target: garden/hackteria
  url: https://hackteria.org/wiki/api.php
  web: https://hackteria.org/wiki/{slug}
  format: mediawiki

- target: garden/idiot
  url: https://wiki.idiot.io
  web: https://web.archive.org/web/*/https://wiki.idiot.io/{slug}
  format: wayback

- target: garden/tami
  url: https://telavivmakers.org
  web: https://web.archive.org/web/*/https://telavivmakers.org/{slug}
  format: wayback

- target: garden/ccczh-news
  url: https://www.ccczh.ch/news/
  web: https://www.ccczh.ch/news/{slug}
  format: website

- target: garden/ccczh-chaosseminar
  url: https://www.ccczh.ch/aktivitaeten/chaosseminar/
  web: https://www.ccczh.ch/aktivitaeten/chaosseminar/{slug}
  format: website

- target: garden/ccczh-vereinsversammlungen
  url: https://www.ccczh.ch/protokolle/
  prefix: https://www.ccczh.ch/protokolle/vereinsversammlungen/
  web: https://www.ccczh.ch/protokolle/vereinsversammlungen/{slug}
  format: website

- target: garden/ccczh-chaostreffs
  url: https://www.ccczh.ch/protokolle/
  prefix: https://www.ccczh.ch/protokolle/beschlussfaehige/
  web: https://www.ccczh.ch/protokolle/beschlussfaehige/{slug}
  format: website

- target: garden/ccczh-vorstandssitzungen
  url: https://www.ccczh.ch/protokolle/
  prefix: https://www.ccczh.ch/protokolle/vorstandssitzungen/
  web: https://www.ccczh.ch/protokolle/vorstandssitzungen/{slug}
  format: website

- target: garden/ccczh-projekte
  url: https://www.ccczh.ch/aktivitaeten/projekte/
  web: https://www.ccczh.ch/aktivitaeten/projekte/{slug}
  format: website

- target: garden/ccczh-aktivitaeten
  url: https://www.ccczh.ch/aktivitaeten/aktivitaeten/
  web: https://www.ccczh.ch/aktivitaeten/aktivitaeten/{slug}
  format: website

- target: garden/ccczh-zugangsgesuche
  url: https://www.ccczh.ch/aktivitaeten/zugangsgesuche/
  web: https://www.ccczh.ch/aktivitaeten/zugangsgesuche/{slug}
  format: website

- target: garden/ccczh-cryptoparties
  url: https://www.ccczh.ch/aktivitaeten/cryptoparties/
  web: https://www.ccczh.ch/aktivitaeten/cryptoparties/{slug}
  format: website

- target: garden/digiges-dossier
  url: https://www.digitale-gesellschaft.ch/dossier/
  web: https://www.digitale-gesellschaft.ch/dossier/{slug}
  format: website

- target: garden/digiges-medienmitteilung
  url: https://www.digitale-gesellschaft.ch/tag/medienmitteilung/
  feed: https://www.digitale-gesellschaft.ch/tag/medienmitteilung/feed/
  web: https://www.digitale-gesellschaft.ch/{slug}
  format: website

- target: garden/elrido
  url: https://elrido.dssr.ch/
  web: https://elrido.dssr.ch/{slug}
  format: website

- target: garden/elrido-mindloot
  url: https://mindloot.net/txt/api.php
  web: https://mindloot.net/txt/{slug}
  format: mediawiki

- target: garden/stahl
  url: https://www.stahlnow.com/projects/
  web: https://www.stahlnow.com/projects/{slug}
  format: website
